services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-vmb-prototype
    container_name: web-vmb-prototype
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - web-vmb-prototype
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-vmb-prototype
    depends_on:
      - app

  db:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - web-vmb-prototype

networks:
  web-vmb-prototype:

volumes:
  dbdata:
