services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vmb-prototype
    container_name: vmb-prototype-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - vmb-prototype
    ports:
      - "8001:9000"

  db:
    image: mysql:lts
    container_name: vmb-prototype-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - vmb-prototype

networks:
  vmb-prototype:

volumes:
  dbdata:
